# Generated by Django 3.2.6 on 2021-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(height_field='50', upload_to='isms/', width_field='50'),
        ),
    ]
