# Generated by Django 3.2.6 on 2021-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0003_alter_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(blank=True, null=True, to='ISMS.Supplier'),
        ),
    ]
