# Generated by Django 3.2.6 on 2021-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0004_auto_20210811_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default='blank'),
        ),
    ]
