# Generated by Django 3.2.6 on 2021-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0005_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(),
        ),
    ]
