# Generated by Django 3.2.6 on 2021-08-15 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0006_alter_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='nic',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
