# Generated by Django 3.2.6 on 2021-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0007_alter_supplier_nic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_body', models.TextField()),
                ('quantity', models.ImageField(upload_to='')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='ordered_items', to='ISMS.Item')),
                ('suppliers', models.ManyToManyField(related_name='request_suppliers', to='ISMS.Supplier')),
            ],
        ),
    ]
