# Generated by Django 3.2.6 on 2021-09-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0008_sendmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
