# Generated by Django 3.1.6 on 2021-09-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0012_auto_20210914_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmail',
            name='items',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_items', to='ISMS.item'),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('suppler_confirmed', 'Suppler confirmed'), ('payment_done', 'Payment done')], default='requested', max_length=200, null=True),
        ),
    ]
