# Generated by Django 3.1.6 on 2021-09-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0013_auto_20210914_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_items', to='ISMS.item'),
        ),
    ]
