# Generated by Django 3.2.6 on 2021-09-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISMS', '0016_alter_confirmedinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedinvoice',
            name='invoice_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ISMS.supplier'),
        ),
    ]
