# Generated by Django 3.2.6 on 2021-08-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('nic', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('maritalStatus', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobRole', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpCode', models.CharField(max_length=20)),
                ('grpAmount', models.FloatField()),
            ],
        ),
    ]
