# Generated by Django 3.2.6 on 2021-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeedata_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/images.jpg', null=True, upload_to=''),
        ),
    ]
