# Generated by Django 3.2.6 on 2021-08-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeedata_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='empStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
