# Generated by Django 3.2.6 on 2021-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employeedata_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='empStatus',
            field=models.BooleanField(default=0),
        ),
    ]
