# Generated by Django 3.2.6 on 2021-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employeedata_empstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='empAdrs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
