# Generated by Django 3.2.6 on 2021-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeedata_empadrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='nic',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='telephone',
            field=models.IntegerField(max_length=10),
        ),
    ]
