# Generated by Django 3.2.6 on 2021-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employeedata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobroles',
            name='jobRole',
            field=models.CharField(max_length=60),
        ),
    ]
