# Generated by Django 3.2.6 on 2021-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_instatus_outstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_at_name', models.CharField(max_length=200, null=True)),
                ('outTime', models.TimeField(null=True)),
                ('inStatus', models.CharField(choices=[('Absent', 'Absent'), ('On Time', 'On Time'), ('Late', 'Late')], default='Absent', max_length=20)),
                ('outStatus', models.CharField(choices=[('Still Working', 'Still Working'), ('On Time', 'On Time'), ('Early', 'Early')], default='Still Working', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='InStatus',
        ),
        migrations.DeleteModel(
            name='outStatus',
        ),
    ]
