# Generated by Django 3.2.6 on 2021-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_attendance_emp_at_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overallStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
