# Generated by Django 3.2.6 on 2021-09-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_attendance_overallstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('inTime', models.TimeField(null=True)),
                ('outTime', models.TimeField(null=True)),
                ('inStatus', models.CharField(choices=[('Absent', 'Absent'), ('On Time', 'On Time'), ('Late', 'Late')], default='Absent', max_length=20)),
                ('outStatus', models.CharField(choices=[('Still Working', 'Still Working'), ('On Time', 'On Time'), ('Early', 'Early')], default='Still Working', max_length=20)),
                ('overallStatus', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20)),
                ('employeeAtData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeedata')),
            ],
        ),
    ]
