# Generated by Django 3.2.6 on 2021-09-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_overallattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverallAttendance',
        ),
    ]
