# Generated by Django 3.2.6 on 2021-09-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_delete_overallattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='attendanaceData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.attendance'),
        ),
    ]
