# Generated by Django 3.2.6 on 2021-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_employeedata_attendanacedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='attendanaceData',
        ),
        migrations.AddField(
            model_name='employeedata',
            name='attendanaceData',
            field=models.ManyToManyField(to='employee.Attendance'),
        ),
    ]
