# Generated by Django 3.2.6 on 2021-09-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20210918_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='attendanaceData',
        ),
        migrations.AddField(
            model_name='employeedata',
            name='attendanaceData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.attendance'),
        ),
    ]
