# Generated by Django 3.2.6 on 2021-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20210918_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overallStatus',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='attendanaceData',
        ),
        migrations.AddField(
            model_name='employeedata',
            name='attendanaceData',
            field=models.ManyToManyField(to='employee.Attendance'),
        ),
    ]
