# Generated by Django 3.2.6 on 2021-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePayments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.IntegerField()),
                ('empName', models.CharField(max_length=100)),
                ('daily_wage', models.FloatField()),
                ('days_worked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('allowance1', models.FloatField()),
                ('allowance2', models.FloatField()),
                ('allowance3', models.FloatField()),
                ('allowance4', models.FloatField()),
                ('deduction1', models.FloatField()),
                ('deduction2', models.FloatField()),
                ('deduction3', models.FloatField()),
                ('deduction4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicSalary', models.FloatField()),
                ('grossPay', models.FloatField()),
                ('netPay', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentTracker',
        ),
        migrations.DeleteModel(
            name='SalaryCalculator',
        ),
    ]
