# Generated by Django 3.2.6 on 2021-08-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0001_initial'),
        ('allowances', '0001_initial'),
        ('employeePayments', '0002_auto_20210816_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netPay', models.FloatField()),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allowances.allowances')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deductions.deductions')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='daily_wage',
            new_name='basicWage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='days_worked',
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeePayments.employee'),
        ),
    ]
