# Generated by Django 3.2.6 on 2021-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePayments', '0003_auto_20210819_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empID',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee',
        ),
        migrations.AddField(
            model_name='payslip',
            name='basicWage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='empName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basicWage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
