# Generated by Django 3.2.6 on 2021-08-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allowances', '0001_initial'),
        ('deductions', '0001_initial'),
        ('employeePayments', '0006_auto_20210820_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empAllow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allowances.allowances'),
        ),
        migrations.AddField(
            model_name='employee',
            name='empDed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deductions.deductions'),
        ),
    ]
