# Generated by Django 3.2.6 on 2021-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePayments', '0008_auto_20210820_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='empID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basicWage',
            field=models.DateField(null=True),
        ),
    ]
