# Generated by Django 3.2.6 on 2021-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supName', models.CharField(max_length=50)),
                ('supEmail', models.EmailField(max_length=254)),
                ('supPhone', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
