# Generated by Django 3.2.6 on 2021-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='roombook_id',
            new_name='reserve_id',
        ),
    ]
